name: Publish Docker image

on:
  push:
    branches: [master]

  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push Docker image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/golinks/gosearch-mcp:latest
            ghcr.io/golinks/gosearch-mcp:${{ github.sha }}
